name = "Handheld Power Tools"
version = "0.0.1"
link = "https://github.com/ShadowBlip/HandyPT"
source = "https://github.com/ShadowBlip/HandyPT"

[author]
name = "Derek J. Clark"
link = "https://github.com/pastaq"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
