name = "Handheld Power Tools"
version = "0.2.0-rc2"
link = "https://github.com/ShadowBlip/HandyPT"
source = "https://github.com/ShadowBlip/HandyPT"

[author]
name = "Derek J. Clark"
link = "https://github.com/pastaq"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = true
