name = "Handheld Power Tools"
version = "0.0.1"
link = "https://github.com/ShadowBlip/HandyPT"
source = "https://github.com/ShadowBlip/HandyPT"
min-crankshaft-version = "0.1.5"

[author]
name = "Derek J. Clark"
link = "https://github.com/pastaq"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = false
