name = "Handheld Power Tools"
version = "0.3.0"
link = "https://github.com/ShadowBlip/HandyPT"
source = "https://github.com/ShadowBlip/HandyPT"

[author]
name = "Derek J. Clark"
link = "https://github.com/pastaq"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = true

[store]
description = """
HandyPT enables TDP control for multiple Aya Neo, OXP, GPD, and other handheld devices, as well as SMT and CPU Boost disable options. This enables the maximum level of control for performance or power saving.

After installing you must run the configuration script. See https://github.com/ShadowBlip/HandyPT for details.

Supports the following:

AMD 3020E, 3050E, 4500U, 4800U, 5560U 5700U, 5800U, 5825U, and 6800U

Intel 1135G7, 1165G7, 1195G7
"""
